apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: alfa-admin
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=       # base64 de "admin"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 de "password"
  POSTGRES_DB: YWRtaW5kYg==     # base64 de "admindb"
