apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  namespace: alfa-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: admin-app
          image: alfa-backend-admin-app:latest
          imagePullPolicy: Never # usar a imagem local se for minikube/kind
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
